# Generated by Django 5.0.14 on 2025-04-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_result_passed_result_percent_result_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('hr', 'HR'), ('admin', 'Администратор')], default='user', max_length=10),
        ),
    ]
